//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace World.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Towns
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Population { get; set; }
        public int CountryId { get; set; }
    
        public virtual Countries Countries { get; set; }
    }
}
