name: angular2_analysis_plugin
version: 0.0.0
description: Dart analyzer plugin for Angular 2
environment:
  sdk: '>=1.9.0-dev.8.0'
dependencies:
  angular2: '0.0.0'
  analyzer: '^0.24.4'
dependency_overrides:
  angular2:
    path: ../../dist/dart/angular2
