name: angular2_material
version: <%= packageJson.version %>
authors:
<%= Object.keys(packageJson.contributors).map(function(name) {
  return '- '+name+' <'+packageJson.contributors[name]+'>';
}).join('\n') %>
description: Google material design components for Angular 2
homepage: <%= packageJson.homepage %>
environment:
  sdk: '>=1.9.0-dev.8.0'
dependencies:
  angular2: '^<%= packageJson.version %>'
  browser: '>=0.10.0 <0.11.0'
dependency_overrides:
  angular2:
    path: ../angular2
